### ISSUE TITLE
Hi , I find some error in RPM.m ,but I dont konw how to fix it.

### ISSUE THREAD

**Issue by li1997522** [gwang-cv/SURF_PIIFD_RPM#3]
My matlab version is 2020a.  

>> SURF_PIIFD_RPM
please wait...
错误使用  * 
用于矩阵乘法的维度不正确。请检查并确保第一个矩阵中的列数与第二个矩阵中的行数匹配。要执行按元素相乘，请使用 '.*'。

出错 eigs>KSherm (line 1365)
        alpha = real(Mv'*r); % to make sure H is Hermitian

出错 eigs>KrylovSchur (line 1281)
    [V, d, isNotConverged, stopAlgorithm] = KSherm(applyOP, applyM, n, k, ...

出错 eigs (line 126)
[V, d, isNotConverged, spdBout, VV] = KrylovSchur(applyOP, applyM, innerOpts, n, k,...

出错 RPM_Lowrank (line 15)
[Q,S]=eigs(@grbf,M,numeig,'lm',OPTS);

出错 RPM/L2E_AGM_Nonrigid (line 131)
        [Q,K]=RPM_Lowrank(X, beta, n_ker, 1);

出错 RPM (line 57)
            [idt, V, param,min_value] = L2E_AGM_Nonrigid(nX, nY-nX, 0.93, r,sigma2);

出错 SURF_PIIFD_RPM (line 107)
    [ys,indx]=RPM(x1,x2);

**Comment by mowuyu** [comment]
I have also encountered this problem. Have you solved it?

**Comment by hjn918** [comment]
I have the same question...

**Comment by gwang-cv** [comment]
I apologize for the delayed response. I just ran it in the Windows 10 + Matlab 2017a environment, and it worked fine. However, there might be an error if run on MacOS. Also, I haven't tested it with higher versions of Matlab on Windows.

**Comment by kaiwenli325** [comment]
This bug can be fixed by #1

**Comment by eshasadia** [comment]
K must be <= Nx

Error in RPM_Lowrank/grbf (line 17)
        [xc , A_k] = fgt_model(Y' , x', hsigma, e,K,p);
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in eigs>KSherm (line 1414)
        r = applyOP(Mv);
            ^^^^^^^^^^^
Error in eigs>KrylovSchur (line 1332)
    [V, d, isNotConverged, stopAlgorithm] = KSherm(applyOP, applyM, n, k, ...
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in eigs (line 126)
[V, d, isNotConverged, spdBout, VV] = KrylovSchur(applyOP, applyM, innerOpts, n, k,...
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in RPM_Lowrank (line 15)
[Q,S]=eigs(@grbf,M,numeig,'lm',OPTS);
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in RPM/L2E_AGM_Nonrigid (line 131)
        [Q,K]=RPM_Lowrank(X, beta, n_ker, 1);
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in RPM (line 57)
            [idt, V, param,min_value] = L2E_AGM_Nonrigid(nX, nY-nX, 0.93, r,sigma2);
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in SURF_PIIFD_RPM (line 107)
    [ys,indx]=RPM(x1,x2);
              ^^^^^^^^^^ facing this error
